### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by brunoocal** [pyannote/pyannote-audio#1109]
Hi, I'm sure this is a newbie question, I'm trying to use diarization with whisper. I have a 2GB GPU and the file I'm trying to use is like 30 seconds and 6MB. I don't know if I'm doing anything wrong or it's just that I need a better gpu. If that's true, what's the VRAM recommended to run this?

I readed in other issue that reducing batch_size could help but I already did that and had no effect whatsoever.

![image](https://user-images.githubusercontent.com/75707587/196825779-de88133c-d106-4abd-981a-4dd3bae28c56.png)

``
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2022.07")
dz = pipeline("audio.wav")
``

Thanks.

**Comment by mflage** [comment]
I'm having the same problem. Did you ever figure this out?

**Comment by mflage** [comment]
I figured it out. I changed the pipeline.embedding_batch_size to 14 and it worked:

```python
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization", use_auth_token="XXXX")
pipeline.embedding_batch_size = 14
```
