### ISSUE TITLE
Massive slowdown in 3.0.0 version from 2.1.1

### ISSUE THREAD

**Issue by mochan-b** [pyannote/pyannote-audio#1523]
I've been using Version 2.1.1  and it would process 1 hour of audio around 15 minutes or so. 

In version 3.0.1, it's been more than 1.5 hours and its still not done for 1 hour of audio.

In both cases I've been using `pipeline.to(torch.device("cuda"))`

So, I'm not using 2.1.1 on `PyPi` but with the `to` function added that was pip installed from github.

I did some basic investigation only. It seems like GPU utilization is lower and CPU utilization is one single core only. 

Before, there was more CPU utilization in more cores.

Profiling shows most time spent on torchaudio functions. There is new message about backends on torchaudio. Could that be a cause? 

Anything else I can look for to narrow down where the performance problem lies?

My code is essentially this. I tried both mp3 and wav audio_file for this.

```python
pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization',
                                        use_auth_token=HUGGING_FACE_API_KEY)
    pipeline.to(torch.device("cuda"))
    diarization = pipeline(audio_file)
```

**Comment by hbredin** [comment]
Try loading the audio first maybe?

```python
from pyannote.audio import Audio
io = Audio(mono='downmix', sample_rate=16000)
waveform, sample_rate = io(audio_file)

diarization = pipeline({"waveform": waveform, "sample_rate": sample_rate})
```

**Comment by grazder** [comment]
I've got the same problem. I've tried to replace onnx providers for embedder model, and it gave me full GPU utilization, but pipeline started to work slower. So in my opinion bottleneck here isn't model, may be it's croping audio or resampling or smth else

**Comment by martinkallstrom** [comment]
Also have the same problem, working on it as we speak. Resampling from 48000 to 16000 hz gives a little speed reduction but nothing remarkable (~10% less). Trying to move the waveform to gpu with `waveform = waveform.to(torch.device("cuda"))` results in an exception in the speaker verification step:

```
  File "/workspace/reason-api/diarize.py", line 75, in __from_audio
    self.annotation, self.embeddings = pipeline(audio, return_embeddings=True, min_speakers=1, max_speakers=3)
  File "/workspace/reason-api/venv/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 325, in __call__
    return self.apply(file, **kwargs)
  File "/workspace/reason-api/venv/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 512, in apply
    embeddings = self.get_embeddings(
  File "/workspace/reason-api/venv/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 344, in get_embeddings
    embedding_batch: np.ndarray = self._embedding(
  File "/workspace/reason-api/venv/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_verification.py", line 609, in __call__
    input_feed={"feats": masked_feature.numpy()[None]},
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.```

**Comment by grazder** [comment]
Yeah, you don't need to transfer waveform to cuda, because model inferences with ONNX runtime, which requires numpy array as input

**Comment by martinkallstrom** [comment]
What then could be the cause of the slow inference? Diarization of 38 seconds of audio takes ~10s, even if done repetitively and measured when models should be loaded into GPU. Which is a surprisingly high real-time factor.

**Comment by grazder** [comment]
I can't identify exact reason right now but I see problems with batching

Here 

https://github.com/pyannote/pyannote-audio/blob/0b45103cb228a81a9d9d776cca92694cb30ddb41/pyannote/audio/pipelines/speaker_verification.py#L544

and here

https://github.com/pyannote/pyannote-audio/blob/0b45103cb228a81a9d9d776cca92694cb30ddb41/pyannote/audio/pipelines/speaker_verification.py#L602

I also right now tried to add `.cuda()` to input waveform.
And added `.cpu()` here

https://github.com/pyannote/pyannote-audio/blob/0b45103cb228a81a9d9d776cca92694cb30ddb41/pyannote/audio/pipelines/speaker_verification.py#L609

And I got a huge increase in speed. Now 204 seconds of audio inferences in 2 seconds instead of 28 seconds previously.

**Comment by grazder** [comment]
So IMO we lose speed in feature generation on CPU

**Comment by grazder** [comment]
Also find out that simple `.cuda()` cast won't work here

https://github.com/pyannote/pyannote-audio/blob/0b45103cb228a81a9d9d776cca92694cb30ddb41/pyannote/audio/pipelines/speaker_verification.py#L581

This doesn't give as much of a speed boost as casting audio to the GPU on input to the pipeline.

**Comment by mochan-b** [comment]
> Try loading the audio first maybe?
> 
> ```python
> from pyannote.audio import Audio
> io = Audio(mono='downmix', sample_rate=16000)
> waveform, sample_rate = io(audio_file)
> 
> diarization = pipeline({"waveform": waveform, "sample_rate": sample_rate})
> ```

Thank you that solved my problem. 

In my test file of 5 minutes, it was first taking 95 seconds with 3.0.1. With 2.1.1, it was taking 9 seconds. 

After passing the down-sampled mono waveform, it is now processing it in 6.7 seconds.

**Comment by jocastrocUnal** [comment]
> Try loading the audio first maybe?
> 
> ```python
> from pyannote.audio import Audio
> io = Audio(mono='downmix', sample_rate=16000)
> waveform, sample_rate = io(audio_file)
> 
> diarization = pipeline({"waveform": waveform, "sample_rate": sample_rate})
> ```

This was my solution also. Thanks

**Comment by hbredin** [comment]
FYI: https://github.com/pyannote/pyannote-audio/issues/1537
