### ISSUE TITLE
CUDA runs out of memory when I test the Speaker Diarization Pipeline from Pyannote.Audio

### ISSUE THREAD

**Issue by qasimali000** [pyannote/pyannote-audio#684]
Hi

I'm trying to test the Speaker Diarization Pipeline which is already provided by Pyannote, but I want to process it via GPU and I'm getting the following error for an audio file which is Seven Minutes Long.

Error:
RUNTIME ERROR: cuda out of memory. Tried to allocate 312.00 MiB (GPU 0; 11.17 GiB total capacity; 1.55 GiB already allocated; 124.69 MiB free; 1.65 GiB reserved in total by PyTorch)

I have tried different versions of CUDA alongwith Pytorch and tensorflow. 

I think there is a memory leak which is causing the memory overload. Here is the code I'm using:

import torch
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')
diarization = pipeline ( {'audio': 'audio.wav'} )

At the last line, it runs out of memory. 

Any help would be appreciated.

Regards

**Comment by Grolaf** [comment]
I don't know if it can help, but I had the same issue when training "speaker change detection".

I followed the tutorial and encountered issue : 

`RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 3.95 GiB total capacity; 2.70 GiB already allocated; 2.81 MiB free; 2.71 GiB reserved in total by PyTorch)`

I fixed it with reducing batch size. You could find the option 

`--batch=SIZE`

when typing : 

`pyannote-audio --help`

Well, it doesn't work. Personnally, I edited the following file : 

`tutorials/models/speaker_change_detection/config.yml     // exported as ${EXP_DIR}/config.yml in the tutorial`

and 

changed 
```
task:
   name: SpeakerChangeDetection
   params:
      duration: 2.0
      batch_size: 64
      per_epoch: 1

```
to
```
task:
   name: SpeakerChangeDetection
   params:
      duration: 2.0
      batch_size: 32
      per_epoch: 1

```

and now it works fine.

**Comment by qasimali000** [comment]
Thank You for the response. I don't really think that it would help me as I am trying to use the Pretrained Pipeline for Speaker Diarization via GPU, the solution you provided is for the training so it won't help much.

Thank you anyways.
